banco_nuevo:
    path:   /nuevo
    defaults: { _controller: "AppBundle:Banco:nuevo"}
    methods:  POST
    
banco_editar:
    path:   /editar
    defaults: { _controller: "AppBundle:Banco:editar"}
    methods:  POST