comision_nuevo:
    path:   /nuevo
    defaults: { _controller: "AppBundle:Comision:nuevo"}
    methods:  POST
    
comision_editar:
    path:   /editar
    defaults: { _controller: "AppBundle:Comision:editar"}
    methods:  POST