modulo_nuevo:
    path:   /nuevo
    defaults: { _controller: "AppBundle:Modulo:nuevo"}
    methods:  POST
    
modulo_editar:
    path:   /editar
    defaults: { _controller: "AppBundle:Modulo:editar"}
    methods:  POST