solicitud_nuevo:
    path:   /nuevo
    defaults: { _controller: "AppBundle:Solicitud:nuevo"}
    methods:  POST
    
solicitud_editar:
    path:   /editar
    defaults: { _controller: "AppBundle:Solicitud:editar"}
    methods:  POST
    
solicitud_reporte:
    path:   /reporte
    defaults: { _controller: "AppBundle:Solicitud:reporte"}
    methods:  POST

solicitud_detallesolrealizadas:
    path:   /detallesolicitud
    defaults: { _controller: "AppBundle:Solicitud:detallesolrealizadas"}
    methods:  POST

solicitud_porfirmar:
    path:   /porfirmar
    defaults: { _controller: "AppBundle:Solicitud:porfirmar"}
    methods:  POST

solicitud_esjefe:
    path:   /esjefe
    defaults: { _controller: "AppBundle:Solicitud:esjefe"}
    methods:  POST
    
solicitud_firmar:
    path:   /firmar
    defaults: { _controller: "AppBundle:Solicitud:firmar"}
    methods:  POST

solicitud_enviarCorreo:
    path:   /enviarCorreo
    defaults: { _controller: "AppBundle:Solicitud:enviarCorreo"}
    methods:  POST
