solicitud_nuevo:
    path:   /nuevo
    defaults: { _controller: "AppBundle:Solicitud:nuevo"}
    methods:  POST
    
solicitud_editar:
    path:   /editar
    defaults: { _controller: "AppBundle:Solicitud:editar"}
    methods:  POST