BackBundle\Entity\Gasto:
    type: entity
    table: gasto
    indexes:
        ciu_gas_fk:
            columns:
                - ciuinf_id
        estinf_gas_fk:
            columns:
                - estinf_id
    uniqueConstraints:
        gasto_pk:
            columns:
                - gas_id
    id:
        gasId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: gas_id
            generator:
                strategy: SEQUENCE
    fields:
        gasFecha:
            type: date
            nullable: true
            column: gas_fecha
        gasValor:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: gas_valor
        gasLocal:
            type: string
            nullable: true
            length: 150
            options:
                fixed: true
            column: gas_local
        gasTipodocumento:
            type: string
            nullable: true
            length: 3
            options:
                fixed: true
            column: gas_tipodocumento
        gasNumerodocumento:
            type: string
            nullable: true
            length: 20
            options:
                fixed: true
            column: gas_numerodocumento
        gasConcepto:
            type: string
            nullable: true
            length: 200
            options:
                fixed: true
            column: gas_concepto
    manyToOne:
        ciuinf:
            targetEntity: CiudadInforme
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ciuinf_id:
                    referencedColumnName: ciuinf_id
            orphanRemoval: false
        estinf:
            targetEntity: EstadoInforme
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                estinf_id:
                    referencedColumnName: estinf_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
