BackBundle\Entity\Informe:
    type: entity
    table: informe
    indexes:
        sol_inf_fk:
            columns:
                - sol_id
    uniqueConstraints:
        informe_pk:
            columns:
                - inf_id
    id:
        infId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: inf_id
            generator:
                strategy: SEQUENCE
    fields:
        infFecharealizacion:
            type: string
            nullable: true
            length: 20
            column: inf_fecharealizacion
        infNumeroactualizacion:
            type: smallint
            nullable: true
            options:
                unsigned: false
            column: inf_numeroactualizacion
        infEstado:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: inf_estado
        infAnio:
            type: string
            nullable: true
            options:
                fixed: true
            column: inf_anio
    manyToOne:
        sol:
            targetEntity: Solicitud
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sol_id:
                    referencedColumnName: sol_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
