BackBundle\Entity\TransporteSolicitadoextra:
    type: entity
    table: transporte_solicitadoextra
    indexes:
        sol_tsolext_fk:
            columns:
                - estsol_id
        ttra_tsolext_fk:
            columns:
                - tiptra_id
    uniqueConstraints:
        transporte_solicitadoextra_pk:
            columns:
                - trasol_id2
    id:
        trasolId2:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: trasol_id2
            generator:
                strategy: SEQUENCE
    fields:
        trasolRutainicio:
            type: string
            nullable: true
            length: 30
            options:
                fixed: true
            column: trasol_rutainicio
        trasolRutafin:
            type: string
            nullable: true
            length: 30
            options:
                fixed: true
            column: trasol_rutafin
        trasolFechasalida:
            type: date
            nullable: true
            column: trasol_fechasalida
        trasolHorasalida:
            type: time
            nullable: true
            column: trasol_horasalida
        trasolFechallegada:
            type: date
            nullable: true
            column: trasol_fechallegada
        trasolHorallegada:
            type: time
            nullable: true
            column: trasol_horallegada
    manyToOne:
        estsol:
            targetEntity: EstadoSolicitud
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                estsol_id:
                    referencedColumnName: estsol_id
            orphanRemoval: false
        tiptra:
            targetEntity: TipoTransporte
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tiptra_id:
                    referencedColumnName: tiptra_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
